config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :vehicles do
    get :assign_driver, on: :collection
    get :assigned_driver_history, on: :collection
  end
  resources :drivers
  resources :vehicles

  root 'welcome#index'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :vehicles
  validates :name, :dob, :licence_class, :issue_date, :licence_number ,presence: true
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :drivers
  validates :make, :model, :variant, :year, :veh_class, :capacity, :vahicle_number,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  def create
    @driver = Driver.new(driver_params)

    if @driver.save
      redirect_to drivers_path, notice: "Driver was created successfully"
    else
      render :new
    end
    licence_class = @driver.licence_class
    @driver.vehicles << Vehicle.where(veh_class: licence_class)
  end

  # PATCH/PUT /drivers/1
  def update
    if @driver.update(driver_params)
      redirect_to drivers_path, notce: 'Driver successfully updated'
    else
      render 'edit'
    end
    licence_class = @driver.licence_class
    @driver.vehicles << Vehicle.where(veh_class: licence_class)
  end

  # DELETE /drivers/1
  def destroy
    if @driver.destroy
      redirect_to drivers_path, notice: 'Driver successfully deleted'
    else
      redirect_to drivers_path, alert: 'Driver deletion failed, please try again!'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :dob, :licence_class, :issue_date, :licence_number, :vehicle_id)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  def index
    @vehicles = Vehicle.all
    @drivers = Driver.all.group_by{|x| x.licence_class}
  end

  # GET /vehicles/1
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to vehicles_path, notice: "Vehicle was created successfully"
    else
      render :new
    end
    veh_class = @vehicle.veh_class
    @vehicle.drivers << Driver.where(licence_class: veh_class)
  end

  # PATCH/PUT /vehicles/1
  def update
    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path, notce: 'Vehicle successfully updated'
    else
      render 'edit'
    end
    veh_class = @vehicle.veh_class
    @vehicle.drivers << Driver.where(licence_class: veh_class)
  end

  # DELETE /vehicles/1
  def destroy
    if @vehicle.destroy
      redirect_to vehicles_path, notice: 'Vehicle successfully deleted'
    else
      redirect_to vehicles_path, alert: 'Vehicle deletion failed, please try again!'
    end
  end

  def assign_driver
    Vehicle.where(id: params[:v_id]).first.update(driver_id: params[:d_id])
    render json: { message: { notice: "Driver Assigned Successfully" } }
  end

  def assigned_driver_history
    @vehicles = Vehicle.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:make, :model, :variant, :year, :veh_class, :capacity, :vahicle_number, :imageUrl, :driver_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :licence_class %><br>
    <%= f.text_field :licence_class %>
  </div>
  <div class="field">
    <%= f.label :issue_date %><br>
    <%= f.date_select :issue_date %>
  </div>
  <div class="field">
    <%= f.label :licence_number %><br>
    <%= f.text_field :licence_number %>
  </div>
  <!-- <div class="field"> -->
    <%#= f.label :vehicle_id %><br>
    <%#= f.number_field :vehicle_id %>
  <!-- </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<h1>Listing Drivers</h1>

<%= link_to 'New Driver', new_driver_path %>

<% unless @drivers.blank? %>
  <div class="table-responsive">
    <table class="table" cellspacing="10">
      <thead>
        <tr>
          <th>Name</th>
          <th>Dob</th>
          <th>Licence Class</th>
          <th>Issue Date</th>
          <th>Licence Number</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @drivers.each do |driver| %>
          <tr>
            <td><%= driver.name %></td>
            <td><%= driver.dob %></td>
            <td><%= driver.licence_class %></td>
            <td><%= driver.issue_date %></td>
            <td><%= driver.licence_number %></td>
            <td><%= link_to 'Show', driver %></td>
            <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
            <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>No records present </p>
<% end %>
  

<br>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @driver.dob %>
</p>

<p>
  <strong>Licence class:</strong>
  <%= @driver.licence_class %>
</p>

<p>
  <strong>Issue date:</strong>
  <%= @driver.issue_date %>
</p>

<p>
  <strong>Licence number:</strong>
  <%= @driver.licence_number %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @driver.vehicles.first.make %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>|Transport|</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :variant %><br>
    <%= f.text_field :variant %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :veh_class %><br>
    <%= f.text_field :veh_class %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :vahicle_number %><br>
    <%= f.text_field :vahicle_number %>
  </div>
  <div class="field">
    <%= f.label :imageUrl %><br>
    <div class="container">
      <div class="avatar-upload">
        <div class="avatar-edit">
          <input type='file' id="imageUpload" accept=".png, .jpg, .jpeg" />
          <label for="imageUpload"></label>
        </div>
      </div>
    </div>
  </div>
  <!-- <div class="field"> -->
    <%#= f.label :driver_id %><br>
    <%#= f.number_field :driver_id %>
  <!-- </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<h1>Listing Vehicles</h1>

<%= link_to 'New Vehicle', new_vehicle_path, :class => "btn btn-sm btn-info pull-right" %>

<% unless @vehicles.blank? %>

  <div class="table-responsive">
    <table class="table" cellspacing="10">
      <thead>
        <tr>
          <th>Make</th>
          <th>Model</th>
          <th>Variant</th>
          <th>Year</th>
          <th>Veh class</th>
          <th>Capacity</th>
          <th>Vahicle number</th>
          <th>Imageurl</th>
          <th>Assign Driver</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @vehicles.each do |vehicle| %>
          <tr>
            <td><%= vehicle.make %></td>
            <td><%= vehicle.model %></td>
            <td><%= vehicle.variant %></td>
            <td><%= vehicle.year %></td>
            <td><%= vehicle.veh_class %></td>
            <td><%= vehicle.capacity %></td>
            <td><%= vehicle.vahicle_number %></td>
            <td><%= vehicle.imageUrl %></td>
            <td><%= select_tag "vehicle_#{vehicle.id}",
            options_for_select(@drivers[vehicle.veh_class].map{|x| [x.name, x.id]}, vehicle.driver_id),
            class: "select required form-control add-select assign-driver", prompt: "Select Driver" rescue "NA"%></td>
            <td><%= link_to 'Show', vehicle %></td>
            <td><%= link_to 'Edit', edit_vehicle_path(vehicle), :class => "btn btn-sm btn-default"%></td>
            <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p>No records present </p>
<% end %>

<br>

<script type="text/javascript">
  $('.assign-driver').on('change', function() {
    var d_assign_path = "<%= assign_driver_vehicles_path %>"
    var v_id = $(this).attr("id").split("_")[1];
    var d_id = $(".assign-driver option:selected").val();
    get_data(d_assign_path, { d_id: d_id, v_id: v_id }, function(data){
      if(data.message.notice != null) {
        alert("Driver Assigned Successfully");
        location.reload();
      } else {
        alert("Error in Assignment");
      }
    });
  });

  function get_data(url, data, callback, data_type){
    return $.ajax({
      url: url,
      dataType: data_type || "json",
      data: data,
      success: function( data ) {
        callback(data);
      },
      error: function(data){
        callback(data);
      }
    });
  }
</script>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @vehicle.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Variant:</strong>
  <%= @vehicle.variant %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Veh class:</strong>
  <%= @vehicle.veh_class %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @vehicle.capacity %>
</p>

<p>
  <strong>Vahicle number:</strong>
  <%= @vehicle.vahicle_number %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @vehicle.imageUrl %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @vehicle.drivers.last.try(:name) %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>

app/views/welcome/index.html.erb
<center><h1>Welcome To Transport Dashboard</h1></center>
<span class="pull-right">
  <%= link_to "Drivers", drivers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %><br><br>
</span>
<span class="pull-left">
  <%= link_to "Vehicles", vehicles_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %><br><br>
</span>
<%= link_to "Assign Drivers", vehicles_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %><br><br>
<%= link_to "Assigned History", assigned_driver_history_vehicles_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>

<!DOCTYPE html>
<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=API_KEY&callback=initMap&region=IN"
    async defer></script>
  </body>
</html>